//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLineOrderWCF.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderLoginSesssionResponse", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Models")]
    public partial class OnLineOrderLoginSesssionResponse : object
    {
        
        private OnLineOrderWCF.Models.OnLineOrderError[] ErrorsField;
        
        private bool IsSucessfulField;
        
        private string OnLineOrderLoginSesssionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Models.OnLineOrderError[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucessful
        {
            get
            {
                return this.IsSucessfulField;
            }
            set
            {
                this.IsSucessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OnLineOrderLoginSesssionKey
        {
            get
            {
                return this.OnLineOrderLoginSesssionKeyField;
            }
            set
            {
                this.OnLineOrderLoginSesssionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderError", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Models")]
    public partial class OnLineOrderError : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription
        {
            get
            {
                return this.ErrorDescriptionField;
            }
            set
            {
                this.ErrorDescriptionField = value;
            }
        }
    }
}
namespace OnLineOrderWCF.Requests
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderProductRequest", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Requests")]
    public partial class OnLineOrderProductRequest : object
    {
        
        private decimal PriceField;
        
        private string ProductDescriptionField;
        
        private string ProductNameField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this.ProductDescriptionField;
            }
            set
            {
                this.ProductDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
}
namespace OnLineOrderWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderCreateProductResponse", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF")]
    public partial class OnLineOrderCreateProductResponse : object
    {
        
        private OnLineOrderWCF.Models.OnLineOrderError[] ErrorsField;
        
        private bool IsSucessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Models.OnLineOrderError[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucessful
        {
            get
            {
                return this.IsSucessfulField;
            }
            set
            {
                this.IsSucessfulField = value;
            }
        }
    }
}
namespace OnLineOrderWCF.Responses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderGetAvailableProductsResponse", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Responses")]
    public partial class OnLineOrderGetAvailableProductsResponse : object
    {
        
        private OnLineOrderWCF.Models.OnLineOrderError[] ErrorsField;
        
        private OnLineOrderWCF.Responses.ProductsResponses[] GetAllProductsField;
        
        private OnLineOrderWCF.Responses.ProductsResponses GetProductField;
        
        private bool IsSucessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Models.OnLineOrderError[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Responses.ProductsResponses[] GetAllProducts
        {
            get
            {
                return this.GetAllProductsField;
            }
            set
            {
                this.GetAllProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Responses.ProductsResponses GetProduct
        {
            get
            {
                return this.GetProductField;
            }
            set
            {
                this.GetProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucessful
        {
            get
            {
                return this.IsSucessfulField;
            }
            set
            {
                this.IsSucessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsResponses", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Responses")]
    public partial class ProductsResponses : object
    {
        
        private decimal PriceField;
        
        private string ProductDescriptionField;
        
        private int ProductIdField;
        
        private string ProductNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this.ProductDescriptionField;
            }
            set
            {
                this.ProductDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineOrderGetAvailableProductsByProductIdResponse", Namespace="http://schemas.datacontract.org/2004/07/OnLineOrderWCF.Responses")]
    public partial class OnLineOrderGetAvailableProductsByProductIdResponse : object
    {
        
        private OnLineOrderWCF.Models.OnLineOrderError[] ErrorsField;
        
        private OnLineOrderWCF.Responses.ProductsResponses GetProductField;
        
        private bool IsSucessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Models.OnLineOrderError[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnLineOrderWCF.Responses.ProductsResponses GetProduct
        {
            get
            {
                return this.GetProductField;
            }
            set
            {
                this.GetProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucessful
        {
            get
            {
                return this.IsSucessfulField;
            }
            set
            {
                this.IsSucessfulField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IOnLineOrder")]
public interface IOnLineOrder
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineOrder/CreateLoginSession", ReplyAction="http://tempuri.org/IOnLineOrder/CreateLoginSessionResponse")]
    System.Threading.Tasks.Task<OnLineOrderWCF.Models.OnLineOrderLoginSesssionResponse> CreateLoginSessionAsync(string username, string passsword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineOrder/CreateProduct", ReplyAction="http://tempuri.org/IOnLineOrder/CreateProductResponse")]
    System.Threading.Tasks.Task<OnLineOrderWCF.OnLineOrderCreateProductResponse> CreateProductAsync(OnLineOrderWCF.Requests.OnLineOrderProductRequest onLineOrderRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineOrder/GetAllAvailableProducts", ReplyAction="http://tempuri.org/IOnLineOrder/GetAllAvailableProductsResponse")]
    System.Threading.Tasks.Task<OnLineOrderWCF.Responses.OnLineOrderGetAvailableProductsResponse> GetAllAvailableProductsAsync(string sessionId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineOrder/GetAvailableProductsByProductId", ReplyAction="http://tempuri.org/IOnLineOrder/GetAvailableProductsByProductIdResponse")]
    System.Threading.Tasks.Task<OnLineOrderWCF.Responses.OnLineOrderGetAvailableProductsByProductIdResponse> GetAvailableProductsByProductIdAsync(string sessionId, int productId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public interface IOnLineOrderChannel : IOnLineOrder, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public partial class OnLineOrderClient : System.ServiceModel.ClientBase<IOnLineOrder>, IOnLineOrder
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public OnLineOrderClient() : 
            base(OnLineOrderClient.GetDefaultBinding(), OnLineOrderClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOnLineOrder.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OnLineOrderClient(EndpointConfiguration endpointConfiguration) : 
            base(OnLineOrderClient.GetBindingForEndpoint(endpointConfiguration), OnLineOrderClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OnLineOrderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(OnLineOrderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OnLineOrderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(OnLineOrderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OnLineOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<OnLineOrderWCF.Models.OnLineOrderLoginSesssionResponse> CreateLoginSessionAsync(string username, string passsword)
    {
        return base.Channel.CreateLoginSessionAsync(username, passsword);
    }
    
    public System.Threading.Tasks.Task<OnLineOrderWCF.OnLineOrderCreateProductResponse> CreateProductAsync(OnLineOrderWCF.Requests.OnLineOrderProductRequest onLineOrderRequest)
    {
        return base.Channel.CreateProductAsync(onLineOrderRequest);
    }
    
    public System.Threading.Tasks.Task<OnLineOrderWCF.Responses.OnLineOrderGetAvailableProductsResponse> GetAllAvailableProductsAsync(string sessionId)
    {
        return base.Channel.GetAllAvailableProductsAsync(sessionId);
    }
    
    public System.Threading.Tasks.Task<OnLineOrderWCF.Responses.OnLineOrderGetAvailableProductsByProductIdResponse> GetAvailableProductsByProductIdAsync(string sessionId, int productId)
    {
        return base.Channel.GetAvailableProductsByProductIdAsync(sessionId, productId);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnLineOrder))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnLineOrder))
        {
            return new System.ServiceModel.EndpointAddress("http://localhost:64495/OnLineOrder.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return OnLineOrderClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOnLineOrder);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return OnLineOrderClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOnLineOrder);
    }
    
    public enum EndpointConfiguration
    {
        
        BasicHttpBinding_IOnLineOrder,
    }
}
